language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
before_script: "bundle exec rake db:migrate"
services:
  - redis-server
gemfile:
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_2.gemfile
